package claude

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/lost-in-the/grove/internal/config"
)

// defaultAllowedDomains are always included in the firewall allowlist.
var defaultAllowedDomains = []string{
	"api.anthropic.com",
	"sentry.io",
	"statsig.anthropic.com",
	"github.com",
	"api.github.com",
	"registry.npmjs.org",
	"pypi.org",
	"files.pythonhosted.org",
	"proxy.golang.org",
	"sum.golang.org",
}

// devcontainerJSON represents the devcontainer.json structure.
type devcontainerJSON struct {
	Name              string                 `json:"name"`
	Image             string                 `json:"image,omitempty"`
	Features          map[string]interface{} `json:"features,omitempty"`
	Mounts            []string               `json:"mounts,omitempty"`
	PostCreateCommand string                 `json:"postCreateCommand,omitempty"`
	InitializeCommand string                 `json:"initializeCommand,omitempty"`
	RemoteEnv         map[string]string      `json:"remoteEnv,omitempty"`
}

// scaffoldDevcontainer creates .devcontainer/devcontainer.json in the worktree.
func scaffoldDevcontainer(worktreePath string, devCfg *config.ClaudeDevcontainerConfig) error {
	devcontainerDir := filepath.Join(worktreePath, ".devcontainer")
	if err := os.MkdirAll(devcontainerDir, 0o755); err != nil {
		return fmt.Errorf("failed to create .devcontainer directory: %w", err)
	}

	worktreeName := filepath.Base(worktreePath)

	dc := devcontainerJSON{
		Name:  fmt.Sprintf("grove-%s", worktreeName),
		Image: "mcr.microsoft.com/devcontainers/base:ubuntu",
		Features: map[string]interface{}{
			"ghcr.io/anthropics/devcontainer-features/claude-code:1.0": map[string]interface{}{},
		},
		Mounts: []string{
			"source=${localWorkspaceFolder}/CLAUDE.md,target=/workspaces/" + worktreeName + "/CLAUDE.md,type=bind,readonly",
		},
		PostCreateCommand: "which grove || echo 'grove CLI not found — install with: go install github.com/lost-in-the/grove/cmd/grove@latest'",
		RemoteEnv: map[string]string{
			"GROVE_AGENT_MODE":      "1",
			"GROVE_NONINTERACTIVE":  "1",
			"ANTHROPIC_API_KEY":     "${localEnv:ANTHROPIC_API_KEY}",
		},
	}

	// Add firewall if enabled
	if devCfg != nil && devCfg.Firewall != nil && *devCfg.Firewall {
		domains := mergeAllowedDomains(devCfg.AllowedDomains)
		if err := generateFirewallScript(devcontainerDir, domains); err != nil {
			return fmt.Errorf("failed to generate firewall script: %w", err)
		}
		dc.InitializeCommand = "chmod +x .devcontainer/init-firewall.sh && .devcontainer/init-firewall.sh"
	}

	data, err := json.MarshalIndent(dc, "", "  ")
	if err != nil {
		return fmt.Errorf("failed to marshal devcontainer.json: %w", err)
	}

	devcontainerPath := filepath.Join(devcontainerDir, "devcontainer.json")
	if err := os.WriteFile(devcontainerPath, append(data, '\n'), 0o644); err != nil {
		return fmt.Errorf("failed to write devcontainer.json: %w", err)
	}

	return nil
}

// mergeAllowedDomains combines default and user-specified domains, deduplicating.
func mergeAllowedDomains(userDomains []string) []string {
	seen := make(map[string]bool, len(defaultAllowedDomains))
	result := make([]string, 0, len(defaultAllowedDomains)+len(userDomains))

	for _, d := range defaultAllowedDomains {
		seen[d] = true
		result = append(result, d)
	}
	for _, d := range userDomains {
		if !seen[d] {
			seen[d] = true
			result = append(result, d)
		}
	}
	return result
}

// generateFirewallScript creates the init-firewall.sh script using iptables.
// This follows the Anthropic devcontainer reference approach.
func generateFirewallScript(devcontainerDir string, allowedDomains []string) error {
	var sb strings.Builder
	sb.WriteString("#!/usr/bin/env bash\n")
	sb.WriteString("# Auto-generated by grove claude plugin — restricts outbound to trusted domains.\n")
	sb.WriteString("# Based on Anthropic devcontainer reference: https://code.claude.com/docs/en/devcontainer\n")
	sb.WriteString("set -euo pipefail\n\n")

	sb.WriteString("ALLOWED_DOMAINS=(\n")
	for _, d := range allowedDomains {
		sb.WriteString(fmt.Sprintf("  %q\n", d))
	}
	sb.WriteString(")\n\n")

	sb.WriteString(`# Resolve domains to IPs and allow them
for domain in "${ALLOWED_DOMAINS[@]}"; do
  ips=$(dig +short "$domain" 2>/dev/null | grep -E '^[0-9]+\.' || true)
  for ip in $ips; do
    iptables -A OUTPUT -d "$ip" -j ACCEPT 2>/dev/null || true
  done
done

# Allow loopback and established connections
iptables -A OUTPUT -o lo -j ACCEPT 2>/dev/null || true
iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT 2>/dev/null || true

# Allow DNS
iptables -A OUTPUT -p udp --dport 53 -j ACCEPT 2>/dev/null || true
iptables -A OUTPUT -p tcp --dport 53 -j ACCEPT 2>/dev/null || true

# Drop everything else
iptables -A OUTPUT -j DROP 2>/dev/null || true

echo "Firewall configured: ${#ALLOWED_DOMAINS[@]} domains allowed"
`)

	scriptPath := filepath.Join(devcontainerDir, "init-firewall.sh")
	return os.WriteFile(scriptPath, []byte(sb.String()), 0o755)
}
